### PR TITLE
Allows macro to be built on older macoOS's

### PR DESCRIPTION
**Pull request by baksha97**
re: #3

### CODE REVIEW

**Comment by tgeisse** [comment]
This library still uses the 'Observation' framework. That framework requires macOS 14+. So, sadly, I cannot bump the requirement down on this library.

**Comment by baksha97** [comment]
There is an important discrepancy between building a library and building a macro. I believe you are mixing up build requirements of swifttools and OS.

When a client app attempts to build with this package with the required swifttools (but a lower macOS version) version, it will mangle the context of the symbols and cause the build to fail. 

For comparison, notice how you can still import the Observation framework - it's simply not available on lower versions. Or for example why swift-syntax has syntax information for older os's frameworks but their min version is macOS 10.15. 


I appreciate the macro that you've shared a lot! For me to use it without this issue, I can maintain my fork. Feel free to disregard this PR if you do not want it. Thanks again 👍

**Comment by tgeisse** [comment]
I see what you mean now. I will get this fixed and released asap.

**Comment by tgeisse** [comment]
Thank you for the appreciation and the contribution! Pull request has been merged and this is now in v0.4.4.

**Pull request merged**
